/** Home page config
 *  ------------------------------------------------------------------------------------------------
**/
import pageSettings from './pageSettings';
import genericContentBlocks from './generic';

const bespokeConfig = {
  name: 'bespoke',
  label: 'Bespoke',
  delete: false,
  file: 'src/bespoke.md',
  slug: '{{slug}}',
  create: false,
  fields: [
    {
      label: 'Bespoke Page',
      name: 'bespokePageInstructions',
      widget: 'instructions',
      flavour: 'header',
      instructions: 'Content for the bespoke page...',
      required: false,
    },
    {
      label: 'Layout',
      name: 'layout',
      widget: 'hidden',
      default: 'layouts/bespoke',
    },
    {
      label: 'Title',
      name: 'title',
      widget: 'string',
      default: 'Bespoke',
    },
    {
      label: 'Hero Image and Page Title',
      name: 'hero',
      widget: 'object',
      fields: [
        {
          label: 'Hero Image',
          name: 'hero',
          widget: 'extraImage',
          showDetails: true,
          required: true,
          hint: 'Minimum width of 1,920px recommended. Anything above 3,000px will be cropped to 3,000px',
        },
        {
          label: 'Pre-Header',
          name: 'preHeader',
          widget: 'string',
          required: false,
          hint: 'smaller text that appears above the header',
        },
        {
          label: 'Header',
          name: 'header',
          widget: 'string',
          required: false,
        },
      ],
    },
    {
      label: 'Introduction Block',
      name: 'bespokeInstructionsOne',
      widget: 'instructions',
      flavour: 'divider',
      instructions: 'Introductory text and images for the bespoke page. Images in this section have a very specific layout and recommended ratios are given under each image upload area.',
      required: false,
    },
    {
      label: 'Introduction',
      name: 'introductionBlock',
      widget: 'object',
      fields: [
        {
          label: 'Pre-Header',
          name: 'preHeader',
          widget: 'string',
          required: false,
          hint: 'smaller text that appears above the header',
        },
        {
          label: 'Header',
          name: 'header',
          widget: 'string',
          required: false,
        },
        {
          label: 'Text Content',
          name: 'text',
          widget: 'markdown',
          required: false,
          buttons: [
            'bold',
            'italic',
            'code',
            'link',
            'heading-one',
            'heading-two',
            'heading-three',
            'heading-four',
            'heading-five',
            'heading-six',
            'quote',
            'code-block',
            'bulleted-list',
            'numbered-list',
          ],
        },
        {
          label: 'Left column image',
          name: 'primaryImage',
          widget: 'extraImage',
          showDetails: true,
        },
        {
          label: 'Sub Images',
          name: 'subImages',
          widget: 'object',
          fields: [
            {
              label: 'One',
              name: 'one',
              widget: 'extraImage',
              showDetails: true,
              hint: 'recommended ratio: 7:9 (700x900px)',
            },
            {
              label: 'Two',
              name: 'two',
              widget: 'extraImage',
              showDetails: true,
              hint: 'recommended ratio: 7:5 (700x500px)',
            },
            {
              label: 'Three',
              name: 'three',
              widget: 'extraImage',
              showDetails: true,
              hint: 'recommended ratio: 7:11 (700x1100px)',
            },
            {
              label: 'Four',
              name: 'four',
              widget: 'extraImage',
              showDetails: true,
              hint: 'recommended ratio: 7:8 (1400x1600px)',
            },
            {
              label: 'Five',
              name: 'five',
              widget: 'extraImage',
              showDetails: true,
              hint: 'recommended ratio: 7:9 (700x900px)',
            },
          ],
        },
      ],
    },
    {
      label: 'Materials Block',
      name: 'bespokeInstructionsMaterials',
      widget: 'instructions',
      flavour: 'divider',
      instructions: 'Displays all available materials alongside the following text content.',
      required: false,
    },
    {
      label: 'Materials',
      name: 'materialsBlock',
      widget: 'object',
      fields: [
        {
          label: 'Hero Image and Section Title',
          name: 'hero',
          widget: 'object',
          fields: [
            {
              label: 'Hero Image',
              name: 'hero',
              widget: 'extraImage',
              showDetails: true,
              required: true,
              hint: 'Minimum width of 1,920px recommended. Anything above 3,000px will be cropped to 3,000px',
            },
            {
              label: 'Header',
              name: 'header',
              widget: 'string',
              required: false,
            },
            {
              label: 'Sub-Header',
              name: 'subHeader',
              widget: 'string',
              required: false,
              hint: 'smaller text that appears below the header',
            },
          ],
        },
        {
          label: 'Pre-Header',
          name: 'preHeader',
          widget: 'string',
          required: false,
          hint: 'smaller text that appears above the header',
        },
        {
          label: 'Header',
          name: 'header',
          widget: 'string',
          required: false,
        },
        {
          label: 'Text Content',
          name: 'text',
          widget: 'markdown',
          required: false,
          buttons: [
            'bold',
            'italic',
            'code',
            'link',
            'heading-one',
            'heading-two',
            'heading-three',
            'heading-four',
            'heading-five',
            'heading-six',
            'quote',
            'code-block',
            'bulleted-list',
            'numbered-list',
          ],
        },
        {
          label: 'CTA Text',
          name: 'cta',
          widget: 'string',
          required: false,
          hint: 'CTA is optional, but recommended.',
        },
        {
          label: 'CTA Link',
          name: 'ctaURL',
          widget: 'string',
          required: false,
          hint: 'CTA is optional, but recommended. If you leave this field blank but provide CTA text the button will open a popup to the CTA/Brochure popup configured in the Fixed Pages menu.',
        },
      ],
    },
    {
      label: 'Fittings Block',
      name: 'bespokeInstructionsFittings',
      widget: 'instructions',
      flavour: 'divider',
      instructions: 'Information about fittings.',
      required: false,
    },
    {
      label: 'Fittings',
      name: 'fittingsBlock',
      widget: 'object',
      fields: [
        {
          label: 'Hero Image and Section Title',
          name: 'hero',
          widget: 'object',
          fields: [
            {
              label: 'Hero Image',
              name: 'hero',
              widget: 'extraImage',
              showDetails: true,
              required: true,
              hint: 'Minimum width of 1,920px recommended. Anything above 3,000px will be cropped to 3,000px',
            },
            {
              label: 'Header',
              name: 'header',
              widget: 'string',
              required: false,
            },
            {
              label: 'Sub-Header',
              name: 'subHeader',
              widget: 'string',
              required: false,
              hint: 'smaller text that appears below the header',
            },
          ],
        },
        {
          label: 'Left Background Image',
          name: 'backLeft',
          widget: 'extraImage',
          showDetails: true,
          required: false,
        },
        {
          label: 'Right Background Image',
          name: 'backRight',
          widget: 'extraImage',
          showDetails: true,
          required: false,
        },
        {
          label: 'Pre-Header',
          name: 'preHeader',
          widget: 'string',
          required: false,
          hint: 'smaller text that appears above the header',
        },
        {
          label: 'Header',
          name: 'header',
          widget: 'string',
          required: false,
        },
        {
          label: 'Text Content',
          name: 'text',
          widget: 'markdown',
          required: false,
          buttons: [
            'bold',
            'italic',
            'code',
            'link',
            'heading-one',
            'heading-two',
            'heading-three',
            'heading-four',
            'heading-five',
            'heading-six',
            'quote',
            'code-block',
            'bulleted-list',
            'numbered-list',
          ],
        },
        {
          label: 'CTA Text',
          name: 'cta',
          widget: 'string',
          required: false,
          hint: 'CTA is optional, but recommended.',
        },
        {
          label: 'CTA Link',
          name: 'ctaURL',
          widget: 'string',
          required: false,
          hint: 'CTA is optional, but recommended. If you leave this field blank but provide CTA text the button will open a popup to the CTA/Brochure popup configured in the Fixed Pages menu.',
        },
      ],
    },
    {
      label: 'Appliances Block',
      name: 'bespokeInstructionsAppliances',
      widget: 'instructions',
      flavour: 'divider',
      instructions: 'Information about Appliances.',
      required: false,
    },
    {
      label: 'Appliances',
      name: 'appliancesBlock',
      widget: 'object',
      fields: [
        {
          label: 'Hero Image and Section Title',
          name: 'hero',
          widget: 'object',
          fields: [
            {
              label: 'Hero Image',
              name: 'hero',
              widget: 'extraImage',
              showDetails: true,
              required: true,
              hint: 'Minimum width of 1,920px recommended. Anything above 3,000px will be cropped to 3,000px',
            },
            {
              label: 'Header',
              name: 'header',
              widget: 'string',
              required: false,
            },
            {
              label: 'Sub-Header',
              name: 'subHeader',
              widget: 'string',
              required: false,
              hint: 'smaller text that appears below the header',
            },
          ],
        },
        {
          label: 'Left Column Image',
          name: 'leftImageOne',
          widget: 'extraImage',
          showDetails: true,
          required: true,
          hint: 'these are stacked in a unique way the second image is offset against the first.',
        },
        {
          label: 'Left Column Secondary Image',
          name: 'leftImageTwo',
          widget: 'extraImage',
          showDetails: true,
          required: false,
          hint: 'these are stacked in a unique way the second image is offset against the first.',
        },
        {
          label: 'Pre-Header',
          name: 'preHeader',
          widget: 'string',
          required: false,
          hint: 'smaller text that appears above the header',
        },
        {
          label: 'Header',
          name: 'header',
          widget: 'string',
          required: false,
        },
        {
          label: 'Text Content',
          name: 'text',
          widget: 'markdown',
          required: false,
          buttons: [
            'bold',
            'italic',
            'code',
            'link',
            'heading-one',
            'heading-two',
            'heading-three',
            'heading-four',
            'heading-five',
            'heading-six',
            'quote',
            'code-block',
            'bulleted-list',
            'numbered-list',
          ],
        },
        {
          label: 'CTA Text',
          name: 'cta',
          widget: 'string',
          required: false,
          hint: 'CTA is optional, but recommended.',
        },
        {
          label: 'CTA Link',
          name: 'ctaURL',
          widget: 'string',
          required: false,
          hint: 'CTA is optional, but recommended. If you leave this field blank but provide CTA text the button will open a popup to the CTA/Brochure popup configured in the Fixed Pages menu.',
        },
      ],
    },
    ...genericContentBlocks,
    {
      label: 'Example Kitchens Block',
      name: 'bespokeInstructionsKitchens',
      widget: 'instructions',
      flavour: 'divider',
      instructions: 'This block showcases example kitchens and lists the materials used by each.',
      required: false,
    },
    {
      label: 'Explore Example Kitchens',
      name: 'kitchensBlock',
      widget: 'object',
      fields: [
        {
          label: 'Section Title',
          name: 'hero',
          widget: 'object',
          fields: [
            {
              label: 'Header',
              name: 'header',
              widget: 'string',
              required: false,
            },
            {
              label: 'Sub-Header',
              name: 'subHeader',
              widget: 'string',
              required: false,
              hint: 'smaller text that appears below the header',
            },
          ],
        },
        {
          label: 'Kitchens',
          name: 'kitchens',
          widget: 'relationWrapped',
          collection: 'kitchen',
          multiple: true,
          searchFields: ['title'],
          valueField: 'title',
          optionsLength: 50,
        },
      ],
    },
    // we also include all of the regular page settings!
    ...pageSettings,
  ], // fields
};

export default bespokeConfig;
