/** Home page config
 *  ------------------------------------------------------------------------------------------------
**/
import pageSettings from './pageSettings';
import genericContentBlocks from './generic';

const contactConfig = {
  name: 'contact',
  label: 'Contact',
  delete: false,
  file: 'src/contact.md',
  slug: '{{slug}}',
  create: false,
  fields: [
    {
      label: 'Contact Page',
      name: 'contactPageInstructions',
      widget: 'instructions',
      flavour: 'header',
      instructions: 'Content for the contact page....',
      required: false,
    },
    {
      label: 'Layout',
      name: 'layout',
      widget: 'hidden',
      default: 'layouts/contact',
    },
    {
      label: 'Title',
      name: 'title',
      widget: 'string',
      default: 'Contact',
    },
    {
      label: 'Hero Image and Page Title',
      name: 'hero',
      widget: 'object',
      fields: [
        {
          label: 'Hero Image',
          name: 'hero',
          widget: 'extraImage',
          showDetails: true,
          required: true,
          hint: 'Minimum width of 1,920px recommended. Anything above 3,000px will be cropped to 3,000px',
        },
        {
          label: 'Pre-Header',
          name: 'preHeader',
          widget: 'string',
          required: false,
          hint: 'smaller text that appears above the header',
        },
        {
          label: 'Header',
          name: 'header',
          widget: 'string',
          required: false,
        },
      ],
    },
    {
      label: 'Contact Form Block',
      name: 'contactInstructionsOne',
      widget: 'instructions',
      flavour: 'divider',
      instructions: 'You cannot customise the form functionality itself from here but can change the text, labels and images surrounding it.',
      required: false,
    },
    {
      label: 'Form content area',
      name: 'formContentArea',
      widget: 'object',
      fields: [
        {
          label: 'Pre-Header',
          name: 'preHeader',
          widget: 'string',
          required: false,
          hint: 'smaller text that appears above the header',
        },
        {
          label: 'Header',
          name: 'header',
          widget: 'string',
          required: false,
        },
        {
          label: 'Text Content',
          name: 'text',
          widget: 'markdown',
          required: false,
          buttons: [
            'bold',
            'italic',
            'code',
            'link',
            'heading-one',
            'heading-two',
            'heading-three',
            'heading-four',
            'heading-five',
            'heading-six',
            'quote',
            'code-block',
            'bulleted-list',
            'numbered-list',
          ],
        },
        {
          label: 'Form Field Labels',
          name: 'labels',
          widget: 'object',
          required: false,
          fields: [
            {
              label: 'Customise Form Labels',
              name: 'contactInstructionsLabels',
              widget: 'instructions',
              flavour: 'vanilla',
              instructions: 'Completely optional, but you can overwrite the labels given to each form field here.',
              required: false,
            },
            {
              label: 'Name',
              name: 'name',
              default: 'Name',
              widget: 'string',
              required: false,
            },
            {
              label: 'Email',
              name: 'email',
              default: 'Email',
              widget: 'string',
              required: false,
            },
            {
              label: 'Subject',
              name: 'subject',
              default: 'Subject',
              widget: 'string',
              required: false,
            },
            {
              label: 'Message',
              name: 'message',
              default: 'Message',
              widget: 'string',
              required: false,
            },
            {
              label: 'Send Message',
              name: 'sendMessage',
              default: 'Send Message',
              widget: 'string',
              required: false,
            },
          ],
        },
        {
          label: 'Decoration images',
          name: 'decorationImages',
          widget: 'list',
          required: false,
          hint: 'Images are lazy-loaded and organised on either side of the contact form. Recommended 6 images. Will be mixed evenly between left and right - if you upload an odd number one will be ignored.',
          fields: [
            {
              label: 'Title',
              name: 'title',
              widget: 'string',
              required: false,
              hint: 'Not used in the site - just for your reference sorting this list!',
            },
            {
              label: 'Image',
              name: 'image',
              widget: 'extraImage',
              showDetails: true,
            },
          ],
        },
      ],
    },
    ...genericContentBlocks,
    {
      label: 'Find Us Block',
      name: 'contactInstructionsFindUs',
      widget: 'instructions',
      flavour: 'divider',
      instructions: 'Address, map and contact details.',
      required: false,
    },
    {
      label: 'Find Us content area',
      name: 'findUsContentArea',
      widget: 'object',
      fields: [
        {
          label: 'Pre-Header',
          name: 'preHeader',
          widget: 'string',
          required: false,
          hint: 'smaller text that appears above the header',
        },
        {
          label: 'Header',
          name: 'header',
          widget: 'string',
          required: false,
        },
        {
          label: 'Address and Telephone numbers',
          name: 'text',
          widget: 'markdown',
          required: false,
          buttons: [
            'bold',
            'italic',
            'code',
            'link',
            'heading-one',
            'heading-two',
            'heading-three',
            'heading-four',
            'heading-five',
            'heading-six',
            'quote',
            'code-block',
            'bulleted-list',
            'numbered-list',
          ],
        },
        {
          label: 'Map embed',
          name: 'mapEmbed',
          widget: 'string',
          required: false,
          default: '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2519.977786759544!2d-0.7924201836467075!3d50.83157536770926!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48745264a0b5d43d%3A0x212878c9e81d7640!2sSylvarna%20Kitchen%20Design!5e0!3m2!1sen!2suk!4v1578706503986!5m2!1sen!2suk" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>',
          hint: 'copy the iframe embed code from the Google Maps `Share` menu. It does not matter what size you choose.',
        },
        // {
        //   label: 'Map Latitude',
        //   name: 'lat',
        //   widget: 'string',
        //   default: '-0.790329',
        //   required: false,
        // },
        // {
        //   label: 'Map Longitude',
        //   name: 'lng',
        //   widget: 'string',
        //   default: '50.8316445',
        //   required: false,
        // },
      ],
    },
    // we also include all of the regular page settings!
    ...pageSettings,
  ], // fields
};

export default contactConfig;
