/** Home page config
 *  ------------------------------------------------------------------------------------------------
**/
import pageSettings from './pageSettings';

const homeConfig = {
  name: 'home',
  label: 'Homepage',
  delete: false,
  file: 'src/index.md',
  slug: '{{slug}}',
  create: false,
  fields: [
    {
      label: 'Home Page',
      name: 'homePageInstructions',
      widget: 'instructions',
      flavour: 'header',
      instructions: 'The home page has a fixed structure but you can customise the content in each block here.',
      required: false,
    },
    {
      label: 'Layout',
      name: 'layout',
      widget: 'hidden',
      default: 'layouts/home',
    },
    {
      label: 'Title',
      name: 'title',
      widget: 'string',
      default: 'Home',
    },
    {
      label: 'Home Page Content: One',
      name: 'homePageInstructionsOne',
      widget: 'instructions',
      flavour: 'divider',
      instructions: 'First content block that is displayed under the Styles carousel on the home page.',
      required: false,
    },
    {
      label: 'First content area',
      name: 'firstContentArea',
      widget: 'object',
      fields: [
        {
          label: 'Pre-Header',
          name: 'preHeader',
          widget: 'string',
          required: false,
          hint: 'smaller text that appears above the header',
        },
        {
          label: 'Header',
          name: 'header',
          widget: 'string',
          required: false,
        },
        {
          label: 'Text Content',
          name: 'text',
          widget: 'markdown',
          required: false,
          buttons: [
            'bold',
            'italic',
            'code',
            'link',
            'heading-one',
            'heading-two',
            'heading-three',
            'heading-four',
            'heading-five',
            'heading-six',
            'quote',
            'code-block',
            'bulleted-list',
            'numbered-list',
          ],
        },
        {
          label: 'CTA Text',
          name: 'cta',
          widget: 'string',
          required: false,
          hint: 'CTA is optional, but recommended.',
        },
        {
          label: 'CTA Link',
          name: 'ctaURL',
          widget: 'string',
          required: false,
          hint: 'CTA is optional, but recommended.',
        },
        {
          label: 'Image',
          name: 'image',
          widget: 'extraImage',
          showDetails: true,
          hint: 'Right aligned image. Designs are portrait in 4:5 ratio',
        },
      ],
    },
    {
      label: 'Home Page Content: Partnerships',
      name: 'homePageInstructionsPartnerships',
      widget: 'instructions',
      flavour: 'divider',
      instructions: 'Final content block on the home page. Focus on partnerships with space for logos/awards etc.',
      required: false,
    },
    {
      label: 'Partnerships content area',
      name: 'partnershipsContentArea',
      widget: 'object',
      fields: [
        {
          label: 'Image',
          name: 'image',
          widget: 'extraImage',
          showDetails: true,
          hint: 'Left aligned image. Appears to the left side of text content on desktops. Designs are landscape in roughly 5:4 ratio',
        },
        {
          label: 'Pre-Header',
          name: 'preHeader',
          widget: 'string',
          required: false,
          hint: 'smaller text that appears above the header',
        },
        {
          label: 'Header',
          name: 'header',
          widget: 'string',
          required: false,
        },
        {
          label: 'Text Content',
          name: 'text',
          widget: 'markdown',
          required: false,
          buttons: [
            'bold',
            'italic',
            'code',
            'link',
            'heading-one',
            'heading-two',
            'heading-three',
            'heading-four',
            'heading-five',
            'heading-six',
            'quote',
            'code-block',
            'bulleted-list',
            'numbered-list',
          ],
        },
        {
          label: 'Logo/Award images',
          name: 'logos',
          widget: 'list',
          required: false,
          hint: 'Right hand column of key logos, partnerships or awards.',
          field: {
            label: 'Logo/Award image',
            name: 'image',
            widget: 'extraImage',
            showDetails: true,
          },
        },
      ],
    },
    // we also include all of the regular page settings!
    ...pageSettings,
  ], // fields
};

export default homeConfig;
