/** Home page config
 *  ------------------------------------------------------------------------------------------------
**/
import pageSettings from './pageSettings';
import genericContentBlocks from './generic';

const kitchenConfig = [
  {
    label: 'Kitchen',
    name: 'kitchenPageInstructions',
    widget: 'instructions',
    instructions: 'Kitchen pages can be assigned to styles.\nThey are normally shown in popups and do not have hero/header images of their own.',
    flavour: 'header',
    required: false,
  },
  {
    label: 'Layout',
    name: 'layout',
    widget: 'hidden',
    default: 'layouts/kitchen',
  },
  {
    label: 'Tags',
    name: 'tags',
    widget: 'hidden',
    default: 'kitchen',
  },
  {
    label: 'Title',
    name: 'title',
    widget: 'string',
    default: 'Kitchen Name',
  },
  {
    label: 'Required Content',
    name: 'kitchenInstructionsOne',
    widget: 'instructions',
    flavour: 'divider',
    instructions: 'This information is shown on the the style page. Other content is hidden until the kitchen popup is opened.',
    required: false,
  },
  {
    label: 'Kitchen Information',
    name: 'kitchenInformation',
    widget: 'object',
    fields: [
      {
        label: 'Location Name/Pre-header',
        name: 'location',
        widget: 'string',
        required: true,
        hint: 'The main header will be the kitchen title. This is intended to be something like `London` or `Modern Luxury`',
      },
      {
        label: 'Kitchen Description',
        name: 'description',
        widget: 'markdown',
        required: false,
        buttons: [
          'bold',
          'italic',
          'code',
          'link',
          'heading-one',
          'heading-two',
          'heading-three',
          'heading-four',
          'heading-five',
          'heading-six',
          'quote',
          'code-block',
          'bulleted-list',
          'numbered-list',
        ],
      },
      {
        label: 'CTA text for style pages',
        name: 'ctaText',
        widget: 'string',
        required: false,
        default: 'See kitchen info',
        hint: 'When we link to this kitchen from a style page, this is the text that will appear in the CTA.',
      },
      {
        label: 'Force Carousel Images to squares?',
        name: 'cover',
        widget: 'boolean',
        required: true,
        default: false,
        hint: 'By default images you upload are fitted within a square frame so that none of the image is cropped. Toggle this option if you would rather your images filled the square frame completely (cropped from the center)',
      },
      {
        label: 'Images',
        name: 'additionalImages',
        required: true,
        widget: 'list',
        showDetails: true,
        hint: 'The first image will be shown on the Style page, all others form part of a carousel in the popup.',
        fields: [
          {
            label: 'Image Name',
            name: 'name',
            widget: 'string',
            required: false,
            hint: 'Just for your own reference when sorting this list!',
          },
          {
            label: 'Image',
            name: 'additionalImage',
            widget: 'extraImage',
            showDetails: true,
          },
        ],
      },
    ],
  },
  ...genericContentBlocks,
  {
    label: 'Materials Used',
    name: 'kitchenPageInstructionsMaterials',
    widget: 'instructions',
    instructions: 'This ties the kitchen to existing materials',
    flavour: 'divider',
    required: false,
  },
  {
    label: 'Materials',
    name: 'materials',
    widget: 'relationWrapped',
    collection: 'material',
    multiple: true,
    searchFields: ['title'],
    valueField: 'title',
    optionsLength: 50,
  },
  {
    label: 'Materials Used Title',
    name: 'materialsUsedTitle',
    widget: 'string',
    required: true,
    default: 'Materials Used',
    hint: 'Defaults to Materials Used but you can change it.',
  },
  {
    label: 'Styles Used',
    name: 'kitchenPageInstructionsStyles',
    widget: 'instructions',
    instructions: 'This ties the kitchen to styles',
    flavour: 'divider',
    required: false,
  },
  {
    label: 'Styles',
    name: 'styles',
    widget: 'relationWrapped',
    collection: 'kitchenStyle',
    multiple: true,
    searchFields: ['title'],
    valueField: 'title',
    optionsLength: 50,
  },
  {
    label: 'Similar Kitchens Title',
    name: 'similarKitchensTitle',
    widget: 'string',
    required: true,
    default: 'Similar Kitchens',
    hint: 'Defaults to Similar Kitchens Used but you can change it.',
  },
  // include general page settings
  ...pageSettings,
];

export default kitchenConfig;
